# Generated by Django 5.2.7 on 2025-10-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HardwareBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bolt_size",
                    models.CharField(
                        choices=[
                            ("M2", "M2"),
                            ("M3", "M3"),
                            ("M4", "M4"),
                            ("M5", "M5"),
                            ("M6", "M6"),
                            ("M8", "M8"),
                            ("M10", "M10"),
                            ("M12", "M12"),
                        ],
                        default="M3",
                        max_length=10,
                    ),
                ),
                (
                    "bolt_head_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("Button Head", "Button Head"),
                            ("Socket Head", "Socket Head"),
                            ("Flat Head", "Flat Head"),
                            ("Pan Head", "Pan Head"),
                            ("Hex Head", "Hex Head"),
                            ("Truss Head", "Truss Head"),
                            ("custom", "Custom"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "custom_bolt_head_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("bolt_slip_fit", models.FloatField()),
                ("press_fit_hex", models.FloatField()),
                ("slip_fit_hex", models.FloatField()),
                ("hex_depth", models.FloatField()),
                ("counter_bore_diameter", models.FloatField()),
                ("counter_bore_depth", models.FloatField()),
                ("counter_sunk_diameter", models.FloatField()),
                ("counter_sunk_chamfer_depth", models.FloatField()),
                ("counter_sunk_chamfer", models.FloatField()),
                ("counter_bore_washer_diameter", models.FloatField()),
                ("counter_bore_washer_depth", models.FloatField()),
                ("square_press_fit", models.FloatField()),
                ("square_slip_fit", models.FloatField()),
                ("square_depth", models.FloatField()),
                ("square_slip_fit_vertical_width", models.FloatField()),
                ("square_slip_fit_vertical_length", models.FloatField()),
                ("square_slip_fit_vertical_depth", models.FloatField()),
                ("heat_insert_diameter", models.FloatField()),
                ("multi_color", models.BooleanField(default=False)),
                (
                    "text_style",
                    models.CharField(
                        choices=[("raised", "Raised"), ("recessed", "Recessed")],
                        default="raised",
                        max_length=10,
                    ),
                ),
                ("text_height", models.FloatField(default=0.4)),
                ("line_width", models.FloatField(default=0.6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
