# Generated by Django 5.2.7 on 2025-10-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_designer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardwareboard",
            name="include_bolt_head_drawing",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="hardwareboard",
            name="line_width",
            field=models.FloatField(default=0.8),
        ),
    ]
