# Generated by Django 5.2.7 on 2025-10-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board_designer", "0002_hardwareboard_include_bolt_head_drawing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hardwareboard",
            name="include_bolt_head_drawing",
        ),
    ]
