# Generated by Django 5.2.7 on 2025-10-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_designer", "0003_remove_hardwareboard_include_bolt_head_drawing"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardwareboard",
            name="heat_insert_depth",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
