# Generated by Django 5.2.7 on 2025-10-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_designer", "0004_hardwareboard_heat_insert_depth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hardwareboard",
            name="multi_color",
        ),
        migrations.RemoveField(
            model_name="hardwareboard",
            name="text_style",
        ),
        migrations.AddField(
            model_name="hardwareboard",
            name="export_mode",
            field=models.CharField(
                choices=[
                    (
                        "multi_recessed",
                        "Multi-Color - Recessed (flush with surface, for multi-material printers)",
                    ),
                    ("multi_raised", "Multi-Color - Raised (above surface)"),
                    ("single_cutout", "Single Color - Cutout (cut into surface)"),
                    ("single_raised", "Single Color - Raised (above surface)"),
                ],
                default="single_raised",
                max_length=20,
            ),
        ),
    ]
